services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aule
      POSTGRES_PASSWORD: aule
      POSTGRES_DB: aule
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    user: "${USER_ID}:${GROUP_ID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    env_file: .env
    command: python -m worker.tasks
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    user: "${USER_ID}:${GROUP_ID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
