version = 0.1

[default.deploy.parameters]
stack_name = "parts-alert-dev"
resolve_s3 = true
s3_prefix = "parts-alert-dev"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
